version: '3.3'
services:
#  traefik:
#    command:
#    - --api.insecure=true
#    - --providers.docker=true
#    - --providers.docker.exposedbydefault=false
#    - --entrypoints.web.address=:80
#    container_name: traefik
#    image: traefik:v2.3
#    ports:
#    - 80:80
#    - 8080:8080
#    volumes:
#    - /var/run/docker.sock:/var/run/docker.sock:ro
  mysql:
    #image: mysql:latest
    container_name: mysql
    build: .
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      # https://hub.docker.com/_/mysql