version: '3.3'
services:
  mysql_server:
    image: mysql
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  benchmark_tpch:
    image: rl-database-indexing_benchmark # image after docker compose build
    build: .
    tty: true
    environment:
      MYSQL_HOST: mysql_server
      PORT: 3306
      DB: tpcd
    volumes:
      - ./generators:/generators
      - ./benchmark_cli:/benchmark_cli
