version: '3.3'
services:
  mysql_server:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  benchmark:
    build: .
    container_name: benchmark_tpch
    environment:
      MYSQL_HOST: 196.168.0.115
      PORT: 3306